#!/bin/bash
Log()
{
    echo "$(date -Is) $1" >> logger.log
    return 0
}

PRESNOOZE=20

cd $(dirname $0)
rm -f pause_logger
echo "" >> logger.log
Log "Snoozing $PRESNOOZE seconds."
sleep $PRESNOOZE
while true; do
    touch strike.log
    Log "Starting lidet.py"
    python3 lidet.py
    Log "lidet.py returned $?"
    if [ -f pause_logger ]; then
        Log "Waiting for pause_logger file to disappear."
        while [ -f pause_logger ]; do
            sleep 1
        done
    else
        Log "Snoozing 5 seconds before restarting."
        sleep 5
    fi
done
